server:
  port: 8001
spring:
  application:
    name: iot-cloud-system
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
# MyBatis-Plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  typeAliasesPackage: com.iot